export const PC_BASE_URL = 'https://raw.githubusercontent.com/Rangi42/polishedcrystal/master'
export const PC_POKEMON_ROUTE = '/gfx/pokemon'
export const PC_SPRITE = '/front.png'
export const PC_PAL_NORMAL = '/normal.pal'
export const PC_PAL_SHINY = '/shiny.pal'
